### ISSUE TITLE
incorrect strings in CSV

### ISSUE THREAD

**Issue by pixel-stuck** [CAS-Atlantic/AArch64-Encoding#1]
in the .csv file given there's a column which lists all of the bits. For example, for addimm
```
-:-:-:-:-:-:-:-:-:-:imm12::::::::::::Rn:::::Rd::::
```
however, these only have 31 bits, rather than 32. So, for example, this string should be:
```
-:-:-:-:-:-:-:-:-:-:imm12::::::::::::Rn:::::Rd:::::
```

**Comment by jeanlego** [comment]
We only use `:` to separate when there two value i.e. `a:b` and not `a:b:` I've checked and it seems alright based on this.
@aarongraham9 If you have a double take on that make sure I'm not crazy.
